### ISSUE TITLE
GPIO API for zeptoforth on the RP2040 should be fixed now

### ISSUE THREAD

**Issue by tabemann** [robzed/ukmarsbot_forth#1]
@robzed The GPIO API for zeptoforth on the RP2040 should be fixed now, just letting you know. (I would have made this a discussion thread rather than an issue if there were a discussion forum on this GitHub.)

**Comment by robzed** [comment]
Removed fixes from encoder.fth and retested. All appears to work.

Anything else for this bug, or can I close?

**Comment by robzed** [comment]
Also added a discussions section.

**Comment by tabemann** [comment]
You can close the issue.
